### ISSUE TITLE
Is a dependency on RxCocoa 5.0.0 required?

### ISSUE THREAD

**Issue by danielt1263** [gringoireDM/RxEnumKit#1]
Can this be set to `~> '5.0'` instead so it can use 5.1?

**Comment by gringoireDM** [comment]
Yes, will bump this up right now. Thank you for pointing this out

**Comment by gringoireDM** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  RxEnumKit (1.0.3) successfully published
 📅  April 9th, 00:29
 🌎  https://cocoapods.org/pods/RxEnumKit
 👍  Tell your friends!
--------------------------------------------------------------------------------
